### ISSUE TITLE
HTMLParser

### ISSUE THREAD

**Issue by ifrstrabalhopoo** [ifrstrabalhopoo/Navegador#6]
Desenvolver parser de HTML

**Comment by Gustavo44** [comment]
Comentário a respeito do código

**Comment by evertoncrespin** [comment]
Em andamento... digamos que uns 50%

**Comment by evertoncrespin** [comment]
Consegui fazer parsing do código fonte de uma página html aleatória na internet para um Document com uma árvore de Nodes
